version: '3.0'
# Define services
services:
  # Logstash Service
  logstash:
    build:
      context: logstash/
    container_name: esp13_logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "52520:52520/tcp"
    expose:
      - "52520"